version: "3.3"
services:
  eurekaserver:
    image: "saidharmareddy/eurekaserver"
    ports:
      - "3001:3001"
    networks:
      - backend
  user:
    image: "saidharmareddy/user"
    ports:
      - "3004:3004"
    networks:
      - backend
    depends_on: 
      - eurekaserver
      - user
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://eurekaserver:3001/eureka
  gateway:
    image: "saidharmareddy/gateway"
    ports:
      - "80:80"
    networks:
      - backend
    depends_on: 
      - eurekaserver
      - user
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://eurekaserver:3001/eureka
networks:
  backend:
    driver: bridge
